# Site settings
author: A.E. 
title: Semiotics & Ciphers
header-img: img/home-bg.png
email: annewiegel17@gmail.com
copyright_name: A.E. 
description: > # this means to ignore newlines until "baseurl:"
  Studies in Signs & Codes
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  missmessae

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
